version: '3'

networks:
  default:
    external: true
    name: integration-test-eth

services:
  hardhat:
    build:
      context: .
      dockerfile: hh-docker/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8545:8545"
