version: '3'

networks:
  default:
    external: true
    name: integration-test-eth

services:
  db:
    build:
      context: ./db
    image: integration-db-eth
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  wiremock:
    image: wiremock/wiremock:2.32.0-1-alpine
    volumes:
      - ./wiremock:/home/wiremock

  identity-service:
    image: ampnet/identity-service:latest
    environment:
      - "spring.profiles.active=dev"
      - "com.ampnet.identityservice.test.enabled-test-kyc=true"
      - "com.ampnet.identityservice.chain-hardhat-testnet.wallet-approver-private-key=0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6"
      - "com.ampnet.identityservice.chain-hardhat-testnet.wallet-approver-service-address=${WALLET_APPROVER_ADDRESS}"
      - "com.ampnet.identityservice.chain-hardhat-testnet.faucet-caller-private-key=0xf214f2b2cd398c806f84e317254e0f0b801d0643303237d97a22a48e01628897"
      - "com.ampnet.identityservice.chain-hardhat-testnet.faucet-service-address=${FAUCET_SERVICE_ADDRESS}"
      - "com.ampnet.identityservice.chain-hardhat-testnet.auto-invest-private-key=0x701b615bbdfb9de65240bc28bd21bbc0d996645a3dd57e7b12bc2bdf6f192c82"
      - "com.ampnet.identityservice.chain-hardhat-testnet.auto-invest-service-address=${AUTO_INVEST_SERVICE_ADDRESS}"
      - "com.ampnet.identityservice.faucet.enabled=true"
      - "com.ampnet.identityservice.auto-invest.enabled=true"
      - "com.ampnet.identityservice.auto-invest.queue.polling=10"
      - "com.ampnet.identityservice.auto-invest.queue.initial-delay=1000"
      - "com.ampnet.identityservice.auto-invest.queue.mining-period=10"
      - "com.ampnet.identityservice.queue.polling=2000"
      - "com.ampnet.identityservice.queue.initial-delay=1000"
      - "com.ampnet.identityservice.queue.mining-period=10"
      - "com.ampnet.identityservice.wallet-approve.gas-limit=20000000"
      - "spring.mail.test-connection=false"
      - "management.health.mail.enabled=false"
    depends_on:
      - db
    ports:
      - "8136:8136"
    volumes:
      - ./logs:/var/log

  report-service:
   image: ampnet/report-service-eth:latest
   environment:
     - "spring.profiles.active=dev"
     - "management.endpoints.web.exposure.include=info,health,prometheus"
     - "com.ampnet.reportserviceeth.queue.polling=100"
     - "com.ampnet.reportserviceeth.queue.initial-delay=5000"
     - "com.ampnet.reportserviceeth.chain-hardhat-testnet.cf-manager-factory-addresses[0]=${CF_MANAGER_FACTORY_ADDRESS_0}"
     - "com.ampnet.reportserviceeth.chain-hardhat-testnet.cf-manager-factory-addresses[1]=${CF_MANAGER_FACTORY_ADDRESS_1}"
     - "com.ampnet.reportserviceeth.chain-hardhat-testnet.snapshot-distributor-addresses[0]=${SNAPSHOT_DISTRIBUTOR_ADDRESS_0}"
     - "com.ampnet.reportserviceeth.chain-hardhat-testnet.start-block-number=0"
     - "com.ampnet.reportserviceeth.chain-hardhat-testnet.num-of-confirmations=0"
     - "com.ampnet.reportserviceeth.chain-mumbai.cf-manager-factory-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-mumbai.cf-manager-factory-addresses[1]="
     - "com.ampnet.reportserviceeth.chain-mumbai.snapshot-distributor-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-matic.cf-manager-factory-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-matic.snapshot-distributor-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-ethereum.cf-manager-factory-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-ethereum.cf-manager-factory-addresses[1]="
     - "com.ampnet.reportserviceeth.chain-ethereum.snapshot-distributor-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-goerli.cf-manager-factory-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-goerli.cf-manager-factory-addresses[1]="
     - "com.ampnet.reportserviceeth.chain-goerli.snapshot-distributor-addresses[0]="
   depends_on:
     - db
   ports:
     - "8137:8137"
   volumes:
     - ./logs:/var/log

  payout-service:
    image: ampnet/payout-service:latest
    environment:
      - "server.port=8138"
      - "spring.profiles.active=dev"
      - "spring.datasource.url=jdbc:postgresql://db:5432/payout_service_eth"
      - "spring.datasource.username=payout_service_eth"
      - "spring.datasource.password=password"
      - "payoutservice.payout.check-asset-owner=false"
      - "payoutservice.ipfs.url=http://wiremock:8080"
      - "payoutservice.ipfs.api-key=api-key"
      - "payoutservice.ipfs.secret-api-key=secret-api-key"
      - "INFURA_ID="
    depends_on:
      - db
      - wiremock
    ports:
      - "8138:8138"
    volumes:
      - ./logs:/var/log
