version: '3'

services:
  db:
    build:
      context: ./db
    image: integration-db-eth
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  identity-service:
    image: ampnet/identity-service:latest
    environment:
      - "spring.profiles.active=dev"
      - "com.ampnet.identityservice.test.enabled-test-kyc=true"
      - "com.ampnet.identityservice.chain-hardhat-testnet.wallet-approver-private-key=0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6"
      - "com.ampnet.identityservice.chain-hardhat-testnet.wallet-approver-service-address=0x610178dA211FEF7D417bC0e6FeD39F05609AD788"
      - "com.ampnet.identityservice.queue.polling=10"
      - "com.ampnet.identityservice.queue.initial-delay=1000"
      - "com.ampnet.identityservice.queue.mining-period=10"
      - "spring.mail.test-connection=false"
      - "management.health.mail.enabled=false"
    depends_on:
       - db
    ports:
       - "8136:8136"

  hardhat:
    build:
      context: .
      dockerfile: hh-docker/Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8545:8545"

  report-service:
   image: ampnet/report-service-eth:latest
   environment:
     - "spring.profiles.active=dev"
     - "management.endpoints.web.exposure.include=info,health,prometheus"
     - "com.ampnet.reportserviceeth.queue.polling=100"
     - "com.ampnet.reportserviceeth.queue.initial-delay=5000"
     - "com.ampnet.reportserviceeth.chain-hardhat-testnet.cf-manager-factory-addresses[0]=0x0165878A594ca255338adfa4d48449f69242Eb8F"
     - "com.ampnet.reportserviceeth.chain-hardhat-testnet.snapshot-distributor-addresses[0]=0xa513E6E4b8f2a923D98304ec87F64353C4D5C853"
     - "com.ampnet.reportserviceeth.chain-hardhat-testnet.start-block-number=0"
     - "com.ampnet.reportserviceeth.chain-hardhat-testnet.num-of-confirmations=0"
     - "com.ampnet.reportserviceeth.chain-mumbai.cf-manager-factory-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-mumbai.cf-manager-factory-addresses[1]="
     - "com.ampnet.reportserviceeth.chain-mumbai.snapshot-distributor-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-matic.cf-manager-factory-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-matic.snapshot-distributor-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-ethereum.cf-manager-factory-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-ethereum.cf-manager-factory-addresses[1]="
     - "com.ampnet.reportserviceeth.chain-ethereum.snapshot-distributor-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-goerli.cf-manager-factory-addresses[0]="
     - "com.ampnet.reportserviceeth.chain-goerli.cf-manager-factory-addresses[1]="
     - "com.ampnet.reportserviceeth.chain-goerli.snapshot-distributor-addresses[0]="
   ports:
     - "8137:8137"
